export type PropKind = "string" | "number" | "boolean" | "enum";

export type PropDescriptor = {
  key: string;
  kind: PropKind;
  label: string;
  helper?: string;
  enumValues?: string[];
  isRegex?: boolean;
};

export type EditorTarget =
  | "row"
  | "field:text"
  | "field:textArea"
  | "field:number"
  | "field:currency"
  | "field:percent"
  | "field:phone"
  | "field:password"
  | "field:ssn"
  | "field:zip"
  | "field:select"
  | "field:multiSelect"
  | "field:checkbox"
  | "field:inlineCheckbox"
  | "field:switch"
  | "field:radio"
  | "field:inlineRadio"
  | "field:date"
  | "field:dateRange";

const sizeEnum = ["sm", "md", "lg"];
const variantEnum = ["outlined", "filled", "standard"];
const ringVariantEnum = ["laser", "expanse", "scanner"];

const rowProp: PropDescriptor = {
  key: "row",
  kind: "number",
  label: "Row",
  helper: "1-based row number",
};

const labelProp: PropDescriptor = { key: "label", kind: "string", label: "Label" };
const helperTextProp: PropDescriptor = {
  key: "helperText",
  kind: "string",
  label: "Helper Text",
};
const requiredProp: PropDescriptor = {
  key: "required",
  kind: "boolean",
  label: "Required",
};
const readOnlyProp: PropDescriptor = {
  key: "readOnly",
  kind: "boolean",
  label: "Read Only",
};
const placeholderProp: PropDescriptor = {
  key: "placeholder",
  kind: "string",
  label: "Placeholder",
};
const sizeProp: PropDescriptor = {
  key: "size",
  kind: "enum",
  label: "Size",
  enumValues: sizeEnum,
};
const variantProp: PropDescriptor = {
  key: "variant",
  kind: "enum",
  label: "Variant",
  enumValues: variantEnum,
};
const ringEnabledProp: PropDescriptor = {
  key: "ringEnabled",
  kind: "boolean",
  label: "Ring Enabled",
};
const animateRingProp: PropDescriptor = {
  key: "animateRingOnFocus",
  kind: "boolean",
  label: "Animate Ring",
};
const ringVariantProp: PropDescriptor = {
  key: "ringVariant",
  kind: "enum",
  label: "Ring Variant",
  enumValues: ringVariantEnum,
};
const optionsProp: PropDescriptor = {
  key: "options",
  kind: "string",
  label: "Options",
  helper: "Comma-separated values, e.g. one, two, three",
};

const textLikeCommon: PropDescriptor[] = [
  rowProp,
  labelProp,
  placeholderProp,
  helperTextProp,
  requiredProp,
  readOnlyProp,
  sizeProp,
  variantProp,
  ringEnabledProp,
  animateRingProp,
  ringVariantProp,
];

export const editorPropsByTarget: Record<EditorTarget, PropDescriptor[]> = {
  row: [
    rowProp,
    sizeProp,
    variantProp,
    ringEnabledProp,
    animateRingProp,
    ringVariantProp,
  ],
  "field:text": [
    ...textLikeCommon,
    { key: "type", kind: "string", label: "Input Type", helper: "text, email, etc" },
    { key: "autoComplete", kind: "string", label: "Auto Complete" },
    { key: "minLength", kind: "number", label: "Min Length" },
    { key: "maxLength", kind: "number", label: "Max Length" },
    { key: "inputMask", kind: "string", label: "Input Mask" },
  ],
  "field:textArea": [
    ...textLikeCommon,
    { key: "autoComplete", kind: "string", label: "Auto Complete" },
    { key: "minLength", kind: "number", label: "Min Length" },
    { key: "maxLength", kind: "number", label: "Max Length" },
    { key: "rows", kind: "number", label: "Rows" },
    { key: "autosize", kind: "boolean", label: "Autosize" },
    { key: "minRows", kind: "number", label: "Min Rows" },
    { key: "maxRows", kind: "number", label: "Max Rows" },
  ],
  "field:number": [
    ...textLikeCommon,
    { key: "maxDigits", kind: "number", label: "Max Digits" },
    { key: "inputMask", kind: "string", label: "Input Mask" },
  ],
  "field:currency": [
    ...textLikeCommon,
    { key: "maxDigits", kind: "number", label: "Max Integer Digits" },
  ],
  "field:percent": [
    ...textLikeCommon,
    { key: "maxDigits", kind: "number", label: "Max Integer Digits" },
  ],
  "field:phone": [
    ...textLikeCommon,
    { key: "inputMask", kind: "string", label: "Input Mask" },
    {
      key: "inputBlocker",
      kind: "string",
      label: "Input Blocker Regex",
      isRegex: true,
    },
  ],
  "field:password": [
    ...textLikeCommon,
    { key: "autoComplete", kind: "string", label: "Auto Complete" },
    { key: "minLength", kind: "number", label: "Min Length" },
    { key: "maxLength", kind: "number", label: "Max Length" },
  ],
  "field:ssn": [
    ...textLikeCommon,
    { key: "maxDigits", kind: "number", label: "Max Digits" },
    { key: "inputMask", kind: "string", label: "Input Mask" },
    {
      key: "inputBlocker",
      kind: "string",
      label: "Input Blocker Regex",
      isRegex: true,
    },
  ],
  "field:zip": [
    ...textLikeCommon,
    { key: "maxDigits", kind: "number", label: "Max Digits" },
    { key: "inputMask", kind: "string", label: "Input Mask" },
    {
      key: "inputBlocker",
      kind: "string",
      label: "Input Blocker Regex",
      isRegex: true,
    },
  ],
  "field:select": [
    rowProp,
    labelProp,
    placeholderProp,
    helperTextProp,
    optionsProp,
    requiredProp,
    readOnlyProp,
    sizeProp,
    variantProp,
    ringEnabledProp,
    animateRingProp,
    ringVariantProp,
  ],
  "field:multiSelect": [
    rowProp,
    labelProp,
    placeholderProp,
    helperTextProp,
    optionsProp,
    requiredProp,
    readOnlyProp,
    {
      key: "searchable",
      kind: "boolean",
      label: "Searchable",
    },
    {
      key: "clearable",
      kind: "boolean",
      label: "Clearable",
    },
    { key: "maxSelected", kind: "number", label: "Max Selected" },
    {
      key: "inline",
      kind: "boolean",
      label: "Inline",
    },
    sizeProp,
    variantProp,
    ringEnabledProp,
    animateRingProp,
    ringVariantProp,
  ],
  "field:checkbox": [
    rowProp,
    labelProp,
    helperTextProp,
    requiredProp,
    readOnlyProp,
    {
      key: "indeterminate",
      kind: "boolean",
      label: "Indeterminate",
    },
    {
      key: "inline",
      kind: "boolean",
      label: "Inline",
    },
    sizeProp,
    variantProp,
    ringEnabledProp,
    animateRingProp,
    ringVariantProp,
  ],
  "field:inlineCheckbox": [
    rowProp,
    labelProp,
    helperTextProp,
    requiredProp,
    readOnlyProp,
    {
      key: "indeterminate",
      kind: "boolean",
      label: "Indeterminate",
    },
    {
      key: "inline",
      kind: "boolean",
      label: "Inline",
    },
    sizeProp,
    variantProp,
    ringEnabledProp,
    animateRingProp,
    ringVariantProp,
  ],
  "field:switch": [
    rowProp,
    labelProp,
    helperTextProp,
    requiredProp,
    readOnlyProp,
    {
      key: "inline",
      kind: "boolean",
      label: "Inline",
    },
    sizeProp,
    variantProp,
    ringEnabledProp,
    animateRingProp,
    ringVariantProp,
  ],
  "field:radio": [
    rowProp,
    labelProp,
    helperTextProp,
    optionsProp,
    requiredProp,
    readOnlyProp,
    {
      key: "inline",
      kind: "boolean",
      label: "Inline",
    },
    sizeProp,
    variantProp,
    ringEnabledProp,
    animateRingProp,
    ringVariantProp,
  ],
  "field:inlineRadio": [
    rowProp,
    labelProp,
    helperTextProp,
    optionsProp,
    requiredProp,
    readOnlyProp,
    {
      key: "inline",
      kind: "boolean",
      label: "Inline",
    },
    sizeProp,
    variantProp,
    ringEnabledProp,
    animateRingProp,
    ringVariantProp,
  ],
  "field:date": [
    rowProp,
    labelProp,
    placeholderProp,
    helperTextProp,
    requiredProp,
    readOnlyProp,
    {
      key: "clearable",
      kind: "boolean",
      label: "Clearable",
    },
    {
      key: "minDate",
      kind: "string",
      label: "Min Date",
      helper: "YYYY-MM-DD",
    },
    {
      key: "maxDate",
      kind: "string",
      label: "Max Date",
      helper: "YYYY-MM-DD",
    },
    {
      key: "disablePast",
      kind: "boolean",
      label: "Disable Past",
    },
    {
      key: "disableFuture",
      kind: "boolean",
      label: "Disable Future",
    },
    {
      key: "disableWeekends",
      kind: "boolean",
      label: "Disable Weekends",
    },
    {
      key: "openOnFocus",
      kind: "boolean",
      label: "Open On Focus",
    },
    {
      key: "closeOnSelect",
      kind: "boolean",
      label: "Close On Select",
    },
    { key: "locale", kind: "string", label: "Locale" },
    { key: "weekStartsOn", kind: "number", label: "Week Starts On (0-6)" },
    ringEnabledProp,
    animateRingProp,
    ringVariantProp,
  ],
  "field:dateRange": [
    rowProp,
    labelProp,
    placeholderProp,
    helperTextProp,
    requiredProp,
    readOnlyProp,
    {
      key: "clearable",
      kind: "boolean",
      label: "Clearable",
    },
    {
      key: "minDate",
      kind: "string",
      label: "Min Date",
      helper: "YYYY-MM-DD",
    },
    {
      key: "maxDate",
      kind: "string",
      label: "Max Date",
      helper: "YYYY-MM-DD",
    },
    {
      key: "disablePast",
      kind: "boolean",
      label: "Disable Past",
    },
    {
      key: "disableFuture",
      kind: "boolean",
      label: "Disable Future",
    },
    {
      key: "disableWeekends",
      kind: "boolean",
      label: "Disable Weekends",
    },
    {
      key: "openOnFocus",
      kind: "boolean",
      label: "Open On Focus",
    },
    {
      key: "closeOnSelect",
      kind: "boolean",
      label: "Close On Select",
    },
    { key: "locale", kind: "string", label: "Locale" },
    { key: "weekStartsOn", kind: "number", label: "Week Starts On (0-6)" },
    ringEnabledProp,
    animateRingProp,
    ringVariantProp,
  ],
};

export const defaultPropsByTarget: Record<EditorTarget, Record<string, unknown>> = {
  row: {
    row: 1,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
  },
  "field:text": {
    row: 1,
    label: "",
    placeholder: "",
    helperText: "",
    required: false,
    readOnly: false,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
    type: "text",
    autoComplete: "",
    minLength: 0,
    maxLength: 120,
    inputMask: "",
  },
  "field:textArea": {
    row: 1,
    label: "",
    placeholder: "",
    helperText: "",
    required: false,
    readOnly: false,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
    autoComplete: "",
    minLength: 0,
    maxLength: 500,
    rows: 3,
    autosize: true,
    minRows: 2,
    maxRows: 8,
  },
  "field:number": {
    row: 1,
    label: "",
    placeholder: "",
    helperText: "",
    required: false,
    readOnly: false,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
    maxDigits: 6,
    inputMask: "",
  },
  "field:currency": {
    row: 1,
    label: "",
    placeholder: "",
    helperText: "",
    required: false,
    readOnly: false,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
    maxDigits: 9,
  },
  "field:percent": {
    row: 1,
    label: "",
    placeholder: "",
    helperText: "",
    required: false,
    readOnly: false,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
    maxDigits: 100,
  },
  "field:phone": {
    row: 1,
    label: "",
    placeholder: "",
    helperText: "",
    required: false,
    readOnly: false,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
    inputMask: "(___) ___-____",
    inputBlocker: "^\\d{0,10}$",
  },
  "field:password": {
    row: 1,
    label: "",
    placeholder: "",
    helperText: "",
    required: false,
    readOnly: false,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
    autoComplete: "",
    minLength: 0,
    maxLength: 120,
  },
  "field:ssn": {
    row: 1,
    label: "",
    placeholder: "",
    helperText: "",
    required: false,
    readOnly: false,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
    maxDigits: 9,
    inputMask: "___-__-____",
    inputBlocker: "^\\d{0,9}$",
  },
  "field:zip": {
    row: 1,
    label: "",
    placeholder: "",
    helperText: "",
    required: false,
    readOnly: false,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
    maxDigits: 9,
    inputMask: "00000[-0000]",
    inputBlocker: "^\\d{0,9}$",
  },
  "field:select": {
    row: 1,
    label: "",
    placeholder: "",
    helperText: "",
    options: [],
    required: false,
    readOnly: false,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
  },
  "field:multiSelect": {
    row: 1,
    label: "",
    placeholder: "",
    helperText: "",
    options: [],
    required: false,
    readOnly: false,
    searchable: true,
    clearable: true,
    maxSelected: 0,
    inline: false,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
  },
  "field:checkbox": {
    row: 1,
    label: "",
    helperText: "",
    required: false,
    readOnly: false,
    indeterminate: false,
    inline: false,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
  },
  "field:inlineCheckbox": {
    row: 1,
    label: "",
    helperText: "",
    required: false,
    readOnly: false,
    indeterminate: false,
    inline: true,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
  },
  "field:switch": {
    row: 1,
    label: "",
    helperText: "",
    required: false,
    readOnly: false,
    inline: false,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
  },
  "field:radio": {
    row: 1,
    label: "",
    helperText: "",
    options: [],
    required: false,
    readOnly: false,
    inline: false,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
  },
  "field:inlineRadio": {
    row: 1,
    label: "",
    helperText: "",
    options: [],
    required: false,
    readOnly: false,
    inline: true,
    size: "md",
    variant: "outlined",
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
  },
  "field:date": {
    row: 1,
    label: "",
    placeholder: "",
    helperText: "",
    required: false,
    readOnly: false,
    clearable: true,
    minDate: "",
    maxDate: "",
    disablePast: false,
    disableFuture: false,
    disableWeekends: false,
    openOnFocus: true,
    closeOnSelect: true,
    locale: "",
    weekStartsOn: 0,
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
  },
  "field:dateRange": {
    row: 1,
    label: "",
    placeholder: "",
    helperText: "",
    required: false,
    readOnly: false,
    clearable: true,
    minDate: "",
    maxDate: "",
    disablePast: false,
    disableFuture: false,
    disableWeekends: false,
    openOnFocus: true,
    closeOnSelect: true,
    locale: "",
    weekStartsOn: 0,
    ringEnabled: true,
    animateRingOnFocus: true,
    ringVariant: "expanse",
  },
};
