import {
  FieldKind,
  type FieldSpec,
  type FormSpec,
  TriggerOperators,
  type TriggerSpec,
  WhenOperators,
} from "../engine/types";
import type {DemoSection} from "./MedicalIntakeFormSpec";

const marketOptionsByExchange: Record<string, {label: string; value: string}[]> = {
  cme: [
    {label: "CME E-mini S&P 500", value: "cme-es"},
    {label: "CME E-mini Nasdaq", value: "cme-nq"},
    {label: "CME Crude Oil", value: "cme-cl"},
    {label: "CME Gold", value: "cme-gc"},
    {label: "CME Euro FX", value: "cme-ec"},
  ],
  nasdaq: [
    {label: "AAPL", value: "nasdaq-aapl"},
    {label: "MSFT", value: "nasdaq-msft"},
    {label: "TSLA", value: "nasdaq-tsla"},
    {label: "NVDA", value: "nasdaq-nvda"},
    {label: "SPY", value: "nasdaq-spy"},
    {label: "QQQ", value: "nasdaq-qqq"},
  ],
  cboe: [
    {label: "CBOE SPY Options", value: "cboe-spy"},
    {label: "CBOE QQQ Options", value: "cboe-qqq"},
    {label: "CBOE IWM Options", value: "cboe-iwm"},
    {label: "CBOE TSLA Options", value: "cboe-tsla"},
    {label: "CBOE NVDA Options", value: "cboe-nvda"},
  ],
  binance: [
    {label: "BTC/USDT", value: "binance-btcusdt"},
    {label: "ETH/USDT", value: "binance-ethusdt"},
    {label: "SOL/USDT", value: "binance-solusdt"},
    {label: "DOGE/USDT", value: "binance-dogeusdt"},
    {label: "XRP/USDT", value: "binance-xrpusdt"},
  ],
};

const applyInitialValues = (
  fields: FieldSpec[],
  initialValues?: Record<string, string>,
): FieldSpec[] => {
  if (!initialValues) return fields;

  return fields.map((field) => {
    if (!Object.prototype.hasOwnProperty.call(initialValues, field.id)) return field;
    return {...field, initialValue: initialValues[field.id]};
  });
};

const marketGateTriggers = (fieldId: string, isComputed = false): TriggerSpec[] => [
  {
    when: {fieldIds: ["tradingMarket"], operator: WhenOperators.isEmpty},
    operations: [
      {fieldIds: [fieldId], operator: TriggerOperators.setHidden, value: true},
      {fieldIds: [fieldId], operator: TriggerOperators.setDisabled, value: true},
      {fieldIds: [fieldId], operator: TriggerOperators.setValue, value: ""},
    ],
  },
  {
    when: {fieldIds: ["tradingMarket"], operator: WhenOperators.notEquals, value: ""},
    operations: [
      {fieldIds: [fieldId], operator: TriggerOperators.setHidden, value: false},
      ...(isComputed
        ? [{fieldIds: [fieldId], operator: TriggerOperators.setDisabled, value: true}]
        : [{fieldIds: [fieldId], operator: TriggerOperators.setDisabled, value: false}]),
    ],
  },
];

const exchangeOnlyTriggers = (fieldId: string, exchange: string): TriggerSpec[] => [
  {
    when: {fieldIds: ["tradingExchange"], operator: WhenOperators.notEquals, value: exchange},
    operations: [
      {fieldIds: [fieldId], operator: TriggerOperators.setHidden, value: true},
      {fieldIds: [fieldId], operator: TriggerOperators.setDisabled, value: true},
      {fieldIds: [fieldId], operator: TriggerOperators.setValue, value: ""},
    ],
  },
];

const buildVisibilityTriggers = (fieldId: string, exchange?: string): TriggerSpec[] => [
  ...marketGateTriggers(fieldId),
  ...(exchange ? exchangeOnlyTriggers(fieldId, exchange) : []),
];

export const buildTradingSystemSections = (
  selectedExchange = "",
  initialValues?: Record<string, string>,
): DemoSection[] => {
  const exchangeValue = selectedExchange;
  const marketOptions = marketOptionsByExchange[exchangeValue] ?? [];

  const marketSection: DemoSection = {
    id: "trading-system",
    title: "Trading System Configuration",
    fields: applyInitialValues(
      [
        {
          id: "tradingExchange",
          kind: FieldKind.select,
          row: 1,
          label: "Exchanges",
          placeholder: "Select exchange",
          required: true,
          options: [
            {label: "CME", value: "cme"},
            {label: "Nasdaq", value: "nasdaq"},
            {label: "Cboe", value: "cboe"},
            {label: "Binance", value: "binance"},
          ],
          size: "md",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          triggers: [
            {
              when: {fieldIds: ["tradingExchange"], operator: WhenOperators.isEmpty},
              operations: [{fieldIds: ["tradingMarket"], operator: TriggerOperators.setValue, value: ""}],
            },
            {
              when: {
                fieldIds: ["tradingExchange"],
                operator: WhenOperators.notEquals,
                value: "cme",
              },
              operations: [{fieldIds: ["cmeContractMultiplier"], operator: TriggerOperators.setValue, value: ""}],
            },
            {
              when: {
                fieldIds: ["tradingExchange"],
                operator: WhenOperators.notEquals,
                value: "binance",
              },
              operations: [{fieldIds: ["binanceMaintenanceMargin"], operator: TriggerOperators.setValue, value: ""}],
            },
            {
              when: {
                fieldIds: ["tradingExchange"],
                operator: WhenOperators.notEquals,
                value: "nasdaq",
              },
              operations: [{fieldIds: ["nasdaqDarkPoolPct"], operator: TriggerOperators.setValue, value: ""}],
            },
            {
              when: {
                fieldIds: ["tradingExchange"],
                operator: WhenOperators.notEquals,
                value: "cboe",
              },
              operations: [{fieldIds: ["cboeOptionPriceStopLossLimit"], operator: TriggerOperators.setValue, value: ""}],
            },
            {
              when: {fieldIds: ["tradingExchange"], operator: WhenOperators.notEquals, value: ""},
              operations: [
                {fieldIds: ["tradingMarket"], operator: TriggerOperators.setDisabled, value: false},
                {fieldIds: ["tradingMarket"], operator: TriggerOperators.setValue, value: ""},
              ],
            },
            {
              when: {fieldIds: ["tradingExchange"], operator: WhenOperators.isEmpty},
              operations: [{fieldIds: ["tradingMarket"], operator: TriggerOperators.setDisabled, value: true}],
            },
          ],
        },
        {
          id: "tradingMarket",
          kind: FieldKind.select,
          row: 1,
          label: "Markets",
          placeholder: "Select market",
          required: true,
          options: marketOptions,
          size: "md",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          disabled: true,
        },
        {
          id: "tradingStrategyType",
          kind: FieldKind.select,
          row: 1,
          label: "Strategy",
          placeholder: "Select strategy",
          options: [
            {label: "Momentum", value: "momentum"},
            {label: "Mean Reversion", value: "mean-reversion"},
            {label: "Spread", value: "spread"},
            {label: "Pair Arbitrage", value: "pair-arb"},
            {label: "Market Making", value: "mm"},
          ],
          required: true,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          triggers: marketGateTriggers("tradingStrategyType"),
        },
        {
          id: "tradingRiskModel",
          kind: FieldKind.select,
          row: 1,
          label: "Risk Profile",
          placeholder: "Select risk model",
          options: [
            {label: "Conservative", value: "conservative"},
            {label: "Balanced", value: "balanced"},
            {label: "Aggressive", value: "aggressive"},
            {label: "Volatility-Scaled", value: "vol-scaled"},
          ],
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          triggers: marketGateTriggers("tradingRiskModel"),
        },
        {
          id: "tradingSessionType",
          kind: FieldKind.select,
          row: 1,
          label: "Session Template",
          placeholder: "Select session",
          options: [
            {label: "Cash RTH", value: "rth"},
            {label: "Extended", value: "extended"},
            {label: "24x7", value: "24x7"},
            {label: "Auction Window", value: "auction"},
          ],
          required: true,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          helperText: "RTH, extended session behavior.",
          triggers: marketGateTriggers("tradingSessionType"),
        },
        {
          id: "tradingPlaybook",
          kind: FieldKind.select,
          row: 2,
          label: "Playbook",
          placeholder: "Select playbook",
          options: [
            {label: "Momentum Pulse", value: "momentum-pulse"},
            {label: "Range Fade", value: "range-fade"},
            {label: "Breakout Ladder", value: "breakout"},
            {label: "Gamma Squeeze", value: "gamma-squeeze"},
            {label: "Options Hedged", value: "options-hedged"},
          ],
          required: true,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          triggers: marketGateTriggers("tradingPlaybook"),
        },
        {
          id: "tradingOrderSide",
          kind: FieldKind.select,
          row: 2,
          label: "Side",
          placeholder: "Select order side",
          options: [
            {label: "Buy", value: "buy"},
            {label: "Sell", value: "sell"},
            {label: "Buy to Cover", value: "buy-to-cover"},
            {label: "Short Sell", value: "short"},
          ],
          required: true,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          triggers: marketGateTriggers("tradingOrderSide"),
        },
        {
          id: "tradingOrderType",
          kind: FieldKind.select,
          row: 2,
          label: "Order Type",
          placeholder: "Select order type",
          options: [
            {label: "Limit", value: "limit"},
            {label: "Market", value: "market"},
            {label: "Stop", value: "stop"},
            {label: "Stop-Limit", value: "stop-limit"},
            {label: "Post-Only", value: "post-only"},
            {label: "Iceberg", value: "iceberg"},
          ],
          required: true,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          helperText: "Some types unlock venue-specific fields.",
          triggers: marketGateTriggers("tradingOrderType"),
        },
        {
          id: "tradingTimeInForce",
          kind: FieldKind.select,
          row: 2,
          label: "Time in Force",
          placeholder: "Select TIF",
          options: [
            {label: "Day", value: "day"},
            {label: "GTC", value: "gtc"},
            {label: "IOC", value: "ioc"},
            {label: "FOK", value: "fok"},
            {label: "GTD", value: "gtd"},
          ],
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          helperText: "IOC/FOK behaviors alter routing.",
          triggers: marketGateTriggers("tradingTimeInForce"),
        },
        {
          id: "tradingRoutingLane",
          kind: FieldKind.select,
          row: 2,
          label: "Routing Lane",
          placeholder: "Select lane",
          options: [
            {label: "Primary Venue", value: "primary"},
            {label: "Dark Pool", value: "dark-pool"},
            {label: "Cross-Exchange", value: "cross-exchange"},
            {label: "Internalized", value: "internalized"},
          ],
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          triggers: marketGateTriggers("tradingRoutingLane"),
        },
        {
          id: "tradingMaxPositionPct",
          kind: FieldKind.percent,
          row: 3,
          label: "Max Position % of Book",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: true,
          helperText: "Hard cap as % of total book.",
          triggers: marketGateTriggers("tradingMaxPositionPct"),
        },
        {
          id: "tradingMaxOrderPct",
          kind: FieldKind.percent,
          row: 3,
          label: "Max Order % per Slice",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: true,
          helperText: "Max percent risk per attempt.",
          triggers: marketGateTriggers("tradingMaxOrderPct"),
        },
        {
          id: "tradingStopLossPct",
          kind: FieldKind.percent,
          row: 3,
          label: "Stop Loss % Floor",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: true,
          helperText: "Soft stop lower bound.",
          triggers: marketGateTriggers("tradingStopLossPct"),
        },
        {
          id: "tradingTakeProfitPct",
          kind: FieldKind.percent,
          row: 3,
          label: "Take Profit % Floor",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: true,
          helperText: "Default target percentage.",
          triggers: marketGateTriggers("tradingTakeProfitPct"),
        },
        {
          id: "tradingTrailingStopPct",
          kind: FieldKind.percent,
          row: 3,
          label: "Trailing Stop %",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          helperText: "Enable for momentum skids.",
          triggers: marketGateTriggers("tradingTrailingStopPct"),
        },
        {
          id: "tradingEntryPrice",
          kind: FieldKind.currency,
          row: 4,
          label: "Entry Price",
          placeholder: "0.00",
          required: true,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          helperText: "Reference for stop/target math.",
          triggers: marketGateTriggers("tradingEntryPrice"),
        },
        {
          id: "tradingStopPrice",
          kind: FieldKind.currency,
          row: 4,
          label: "Stop Price",
          placeholder: "0.00",
          required: false,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          helperText: "Input both entry and stop for auto distance.",
          triggers: marketGateTriggers("tradingStopPrice"),
        },
        {
          id: "tradingStopDistancePct",
          kind: FieldKind.percent,
          row: 4,
          label: "Stop Distance % (Computed)",
          placeholder: "0.00",
          required: false,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          disabled: true,
          readOnly: true,
          helperText: "Auto-calculated from entry and stop prices.",
          triggers: marketGateTriggers("tradingStopDistancePct", true),
        },
        {
          id: "tradingTakeProfitPrice",
          kind: FieldKind.currency,
          row: 4,
          label: "Take Profit Price",
          placeholder: "0.00",
          required: false,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          helperText: "Input both targets for R/R check.",
          triggers: marketGateTriggers("tradingTakeProfitPrice"),
        },
        {
          id: "tradingRewardToRiskPct",
          kind: FieldKind.percent,
          row: 4,
          label: "Reward/Risk % (Computed)",
          placeholder: "0.00",
          required: false,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          disabled: true,
          readOnly: true,
          helperText: "Auto-computed when entry/stop/tp are set.",
          triggers: marketGateTriggers("tradingRewardToRiskPct", true),
        },
        {
          id: "tradingPositionValue",
          kind: FieldKind.currency,
          row: 5,
          label: "Position Notional",
          placeholder: "0.00",
          required: true,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          helperText: "Gross value before account ratio math.",
          triggers: marketGateTriggers("tradingPositionValue"),
        },
        {
          id: "tradingAccountEquity",
          kind: FieldKind.currency,
          row: 5,
          label: "Account Equity",
          placeholder: "0.00",
          required: true,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          helperText: "Used for percentage sizing.",
          triggers: marketGateTriggers("tradingAccountEquity"),
        },
        {
          id: "tradingAllocationPct",
          kind: FieldKind.percent,
          row: 5,
          label: "Allocation % (Computed)",
          placeholder: "0.00",
          required: false,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          disabled: true,
          readOnly: true,
          helperText: "Position notional / account equity.",
          triggers: marketGateTriggers("tradingAllocationPct", true),
        },
        {
          id: "tradingMakerRebate",
          kind: FieldKind.percent,
          row: 5,
          label: "Maker Rebate % (Grid)",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          triggers: marketGateTriggers("tradingMakerRebate"),
        },
        {
          id: "tradingTakerFee",
          kind: FieldKind.percent,
          row: 5,
          label: "Taker Fee % (Grid)",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          triggers: marketGateTriggers("tradingTakerFee"),
        },
        {
          id: "tradingSlippageCap",
          kind: FieldKind.percent,
          row: 6,
          label: "Slippage Cap %",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: true,
          triggers: marketGateTriggers("tradingSlippageCap"),
        },
        {
          id: "tradingVolatilityShock",
          kind: FieldKind.percent,
          row: 6,
          label: "Volatility Shock %",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          triggers: marketGateTriggers("tradingVolatilityShock"),
        },
        {
          id: "tradingSignalConfidence",
          kind: FieldKind.percent,
          row: 6,
          label: "Signal Confidence %",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: true,
          helperText: "Model confidence gate.",
          triggers: marketGateTriggers("tradingSignalConfidence"),
        },
        {
          id: "tradingOrderQty",
          kind: FieldKind.number,
          row: 6,
          label: "Order Qty",
          placeholder: "10000",
          maxDigits: 8,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: true,
          helperText: "Integer quantity.",
          triggers: marketGateTriggers("tradingOrderQty"),
        },
        {
          id: "tradingMinFill",
          kind: FieldKind.number,
          row: 7,
          label: "Minimum Fill",
          placeholder: "0",
          maxDigits: 8,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          helperText: "Minimum clip size to rest.",
          triggers: marketGateTriggers("tradingMinFill"),
        },
        {
          id: "tradingIocWindowMs",
          kind: FieldKind.number,
          row: 7,
          label: "IOC Window (ms)",
          placeholder: "150",
          maxDigits: 6,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          helperText: "For time slicing.",
          triggers: marketGateTriggers("tradingIocWindowMs"),
        },
        {
          id: "tradingVolWindowSec",
          kind: FieldKind.number,
          row: 7,
          label: "Vol Window (s)",
          placeholder: "300",
          maxDigits: 6,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          helperText: "Rolling window for volatility calc.",
          triggers: marketGateTriggers("tradingVolWindowSec"),
        },
        {
          id: "tradingOrderPriority",
          kind: FieldKind.select,
          row: 7,
          label: "Priority Bucket",
          placeholder: "Select bucket",
          options: [
            {label: "Low", value: "low"},
            {label: "Normal", value: "normal"},
            {label: "High", value: "high"},
            {label: "Critical", value: "critical"},
          ],
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          triggers: marketGateTriggers("tradingOrderPriority"),
        },
        {
          id: "cmeContractMultiplier",
          kind: FieldKind.number,
          row: 8,
          label: "CME Contract Multiplier",
          placeholder: "50",
          required: false,
          maxDigits: 6,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          helperText: "CME only.",
          triggers: buildVisibilityTriggers("cmeContractMultiplier", "cme"),
        },
        {
          id: "cmeSettlementType",
          kind: FieldKind.select,
          row: 8,
          label: "CME Settlement Type",
          placeholder: "Select settlement",
          options: [
            {label: "Physical", value: "physical"},
            {label: "Cash", value: "cash"},
            {label: "EFP", value: "efp"},
          ],
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          triggers: buildVisibilityTriggers("cmeSettlementType", "cme"),
        },
        {
          id: "cmeDailyLimit",
          kind: FieldKind.currency,
          row: 8,
          label: "CME Daily Limit",
          placeholder: "0.00",
          required: false,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          helperText: "CME limit order cap.",
          triggers: buildVisibilityTriggers("cmeDailyLimit", "cme"),
        },
        {
          id: "cmeLimitUpDown",
          kind: FieldKind.percent,
          row: 8,
          label: "CME Limit Up/Down %",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          triggers: buildVisibilityTriggers("cmeLimitUpDown", "cme"),
        },
        {
          id: "binanceMaintenanceMargin",
          kind: FieldKind.percent,
          row: 9,
          label: "Binance Maintenance Margin %",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          helperText: "Binance perpetual only.",
          triggers: buildVisibilityTriggers("binanceMaintenanceMargin", "binance"),
        },
        {
          id: "binanceLiquidationBuffer",
          kind: FieldKind.percent,
          row: 9,
          label: "Binance Liquidation Buffer %",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          helperText: "Additional safety margin.",
          triggers: buildVisibilityTriggers("binanceLiquidationBuffer", "binance"),
        },
        {
          id: "binanceFundingTolerance",
          kind: FieldKind.percent,
          row: 9,
          label: "Binance Funding Tolerance %",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          helperText: "Tolerance threshold for funding spikes.",
          triggers: buildVisibilityTriggers("binanceFundingTolerance", "binance"),
        },
        {
          id: "binanceMaxOpenInterest",
          kind: FieldKind.number,
          row: 9,
          label: "Binance Max Open Interest",
          placeholder: "250",
          maxDigits: 7,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          helperText: "Open interest cap override.",
          triggers: buildVisibilityTriggers("binanceMaxOpenInterest", "binance"),
        },
        {
          id: "binanceLeverageTier",
          kind: FieldKind.select,
          row: 9,
          label: "Binance Leverage Tier",
          placeholder: "Select tier",
          options: [
            {label: "Cross (x3)", value: "cross-3"},
            {label: "Isolated (x5)", value: "isolated-5"},
            {label: "Isolated (x10)", value: "isolated-10"},
            {label: "Isolated (x20)", value: "isolated-20"},
            {label: "Isolated (x50)", value: "isolated-50"},
          ],
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          helperText: "Binance venue constraint.",
          triggers: buildVisibilityTriggers("binanceLeverageTier", "binance"),
        },
        {
          id: "nasdaqDarkPoolPct",
          kind: FieldKind.percent,
          row: 10,
          label: "Nasdaq Dark-Pool Share %",
          placeholder: "0.00",
          required: false,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          helperText: "Nasdaq only.",
          triggers: buildVisibilityTriggers("nasdaqDarkPoolPct", "nasdaq"),
        },
        {
          id: "nasdaqRoutePreference",
          kind: FieldKind.select,
          row: 10,
          label: "Nasdaq Route Preference",
          placeholder: "Select route",
          options: [
            {label: "Primary", value: "primary"},
            {label: "Dark", value: "dark"},
            {label: "NBBO Blend", value: "nbbo"},
            {label: "RFQ", value: "rfq"},
          ],
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          triggers: buildVisibilityTriggers("nasdaqRoutePreference", "nasdaq"),
        },
        {
          id: "nasdaqBorrowFee",
          kind: FieldKind.currency,
          row: 10,
          label: "Nasdaq Borrow Fee",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          helperText: "Short-borrowed fee floor.",
          triggers: buildVisibilityTriggers("nasdaqBorrowFee", "nasdaq"),
        },
        {
          id: "nasdaqBorrowUtilization",
          kind: FieldKind.percent,
          row: 10,
          label: "Borrow Utilization %",
          placeholder: "0.00",
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          triggers: buildVisibilityTriggers("nasdaqBorrowUtilization", "nasdaq"),
        },
        {
          id: "cboeOptionRoot",
          kind: FieldKind.select,
          row: 11,
          label: "Option Root",
          placeholder: "Select root",
          options: [
            {label: "SPY", value: "spy"},
            {label: "QQQ", value: "qqq"},
            {label: "IWM", value: "iwm"},
            {label: "TSLA", value: "tsla"},
          ],
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          required: false,
          helperText: "CBOE options only.",
          triggers: buildVisibilityTriggers("cboeOptionRoot", "cboe"),
        },
        {
          id: "cboeOptionExpiry",
          kind: FieldKind.date,
          row: 11,
          label: "Option Expiry",
          placeholder: "YYYY-MM-DD",
          required: false,
          clearable: true,
          closeOnSelect: true,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          triggers: buildVisibilityTriggers("cboeOptionExpiry", "cboe"),
        },
        {
          id: "cboeOptionStrike",
          kind: FieldKind.currency,
          row: 11,
          label: "Option Strike",
          placeholder: "0.00",
          required: false,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          helperText: "Use for option-style strategies.",
          triggers: buildVisibilityTriggers("cboeOptionStrike", "cboe"),
        },
        {
          id: "cboeOptionPriceStopLossLimit",
          kind: FieldKind.currency,
          row: 11,
          label: "Option Price Stop Loss Limit",
          placeholder: "0.00",
          required: false,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          helperText: "Option stop-loss level target.",
          triggers: buildVisibilityTriggers("cboeOptionPriceStopLossLimit", "cboe"),
        },
        {
          id: "cboeOptionTakeProfitLimit",
          kind: FieldKind.currency,
          row: 11,
          label: "Option Price Take Profit Limit",
          placeholder: "0.00",
          required: false,
          size: "sm",
          variant: "outlined",
          ringEnabled: true,
          animateRingOnFocus: true,
          triggers: buildVisibilityTriggers("cboeOptionTakeProfitLimit", "cboe"),
        },
      ],
      initialValues,
    ),
  };

  return [marketSection];
};

export const buildTradingSystemFormSpec = (
  selectedExchange = "",
  initialValues?: Record<string, string>,
): FormSpec => {
  const sections = buildTradingSystemSections(selectedExchange, initialValues);

  return {
    id: "trading-system",
    fields: sections.flatMap((section) => section.fields),
  };
};
